# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: ruby:2.6.3

jobs:
  build:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - gem1-{{ checksum "Gemfile.lock" }}
            - gem1-
      - checkout
      - run: bundle install --path vendor/bundle
      - run: cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
      - run: openssl aes-256-cbc -k "$DECRYPT_KEY" -in twitter_config.yml.enc -out twitter_config.yml -d
      - run: bash -xe main.sh
      - save_cache:
          key: gem1-{{ checksum "Gemfile.lock" }}
          paths:
            - "vendor"
            - ".bundle"

filtersBranchesOnlyMaster: &filtersBranchesOnlyMaster
  filters:
    branches:
      only:
        - master

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          <<: *filtersBranchesOnlyMaster
          cron: "15 0 * * *"
    jobs:
      - build
